[target.thumbv6m-none-eabi]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP2040",
  "--speed",
  "5000",
  "--log-format",
  "{L} {s}",
]

linker = "flip-link"


rustflags = [
  "-C", "linker=flip-link", # <- add this
  # (..)
]

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"