[book]
authors = ["Geoff Jacobsen"]
language = "en"
multilingual = false
src = "src"
title = "The RPK Guide Book"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/jacott/rpk"
